apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    srv: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      srv: api-gateway
  template:
    metadata:
      labels:
        srv: api-gateway
    spec:
      restartPolicy: Always
      containers:
      - name: api-gateway
        image: springcommunity/spring-petclinic-api-gateway
        resources:
          limits:
            memory: "512M"
        command: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "org.springframework.boot.loader.JarLauncher"]
        ports:
        - name: port8080
          containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  selector:
    srv: api-gateway
  ports:
    - port: 8080
      targetPort: 8080