apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  labels:
    srv: config-server
spec:
  replicas: 2
  selector:
    matchLabels:
      srv: config-server
  template:
    metadata:
      labels:
        srv: config-server
    spec:
      restartPolicy: Always
      containers:
      - name: config-server
        image: springcommunity/spring-petclinic-config-server
        resources:
          limits:
            memory: "512M"
        ports:
        - name: port8888
          containerPort: 8888

---
apiVersion: v1
kind: Service
metadata:
  name: config-server
spec:
  selector:
    srv: config-server
  ports:
    - port: 8888
      targetPort: 8888