apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers-service
  labels:
    srv: customers-service
spec:
  replicas: 2
  selector:
    matchLabels:
      srv: customers-service
  template:
    metadata:
      labels:
        srv: customers-service
    spec:
      restartPolicy: Always
      containers:
      - name: customers-service
        image: springcommunity/spring-petclinic-customers-service
        resources:
          limits:
            memory: "512M"
        command: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "org.springframework.boot.loader.JarLauncher"]
        ports:
        - name: port8081
          containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: customers-service
spec:
  selector:
    srv: customers-service
  ports:
    - port: 8081
      targetPort: 8081