apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
  labels:
    srv: discovery-server
spec:
  replicas: 2
  selector:
    matchLabels:
      srv: discovery-server
  template:
    metadata:
      labels:
        srv: discovery-server
    spec:
      restartPolicy: Always
      containers:
      - name: discovery-server
        image: springcommunity/spring-petclinic-discovery-server
        resources:
          limits:
            memory: "512M"
        command: ["./dockerize","-wait=tcp://config-server:8888","-timeout=60s","--","java", "org.springframework.boot.loader.JarLauncher"]
        ports:
        - name: port8761
          containerPort: 8761

---
apiVersion: v1
kind: Service
metadata:
  name: discovery-server
spec:
  selector:
    srv: discovery-server
  ports:
    - port: 8761
      targetPort: 8761