apiVersion: apps/v1
kind: Deployment
metadata:
  name: vets-service
  labels:
    srv: vets-service
spec:
  replicas: 2
  selector:
    matchLabels:
      srv: vets-service
  template:
    metadata:
      labels:
        srv: vets-service
    spec:
      restartPolicy: Always
      containers:
      - name: vets-service
        image: springcommunity/spring-petclinic-vets-service
        resources:
          limits:
            memory: "512M"
        command: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "org.springframework.boot.loader.JarLauncher"]
        ports:
        - name: port8083
          containerPort: 8083

---
apiVersion: v1
kind: Service
metadata:
  name: vets-service
spec:
  selector:
    srv: vets-service
  ports:
    - port: 8083
      targetPort: 8083